// Code generated by MockGen. DO NOT EDIT.
// Source: log.go

// Package log is a generated GoMock package.
package log

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	args "github.com/release-engineering/exodus-rsync/internal/args"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// NewLogger mocks base method.
func (m *MockInterface) NewLogger(arg0 args.Config) *Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLogger", arg0)
	ret0, _ := ret[0].(*Logger)
	return ret0
}

// NewLogger indicates an expected call of NewLogger.
func (mr *MockInterfaceMockRecorder) NewLogger(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLogger", reflect.TypeOf((*MockInterface)(nil).NewLogger), arg0)
}
