// Code generated by MockGen. DO NOT EDIT.
// Source: diag.go
//
// Generated by this command:
//
//	mockgen -package diag -destination mock.go -source diag.go
//

// Package diag is a generated GoMock package.
package diag

import (
	context "context"
	reflect "reflect"

	args "github.com/release-engineering/exodus-rsync/internal/args"
	conf "github.com/release-engineering/exodus-rsync/internal/conf"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockInterface) Run(arg0 context.Context, arg1 conf.Config, arg2 args.Config) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", arg0, arg1, arg2)
}

// Run indicates an expected call of Run.
func (mr *MockInterfaceMockRecorder) Run(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockInterface)(nil).Run), arg0, arg1, arg2)
}
