name: Make tag

on:
  workflow_dispatch: {}
  release:
    types: [published]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # we don't want a shallow clone because we want to use "git describe"
        fetch-depth: 0

    - name: Get version from changelog
      run: sed -r -n -e '/^## [0-9.]+/ { s|^## ([0-9.]+).*|::set-output name=version::\1|p; q }' CHANGELOG.md
      id: get_version

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21-bookworm

    - name: Compile
      run: make BUILDVERSION=v${{ steps.get_version.outputs.version }}

    - name: Ensure tag exists
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.get_version.outputs.version }}
        create_annotated_tag: true

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          exodus-rsync
        tag_name: v${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
